name: Matrix Calculator CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ doxygen graphviz make valgrind

    - name: Build application and tests
      run: make all

    - name: Run unit tests
      run: ./test_app

    - name: Generate documentation
      run: make doc

    - name: Check for memory leaks
      run: valgrind --leak-check=full --error-exitcode=1 ./test_app